package com.xiaoming.controller;

import com.xiaoming.model.MyUser;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import com.xiaoming.model.MyUserRepository;

/**
 * @author Xiaoming.
 * Created with IntelliJ IDEA on 2018/11/22 11:40.
 * Description :
 */
@RestController
public class Sign {
    @Autowired // This means to get the bean called userRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private MyUserRepository userRepository;

    @RequestMapping(method = /*RequestMethod.POST*/RequestMethod.GET, path = "/signup")
    public MyUser signUp(@RequestParam(value = "username")String name, @RequestParam(value = "password")String psw, @RequestParam(value = "email")String email){
        MyUser u = new MyUser();
        u.setNickName(name);
        u.setPassword(psw);
        u.setEmail(email);
        userRepository.save(u);

        return u;
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<MyUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
